#lang pollen

◊(define-meta title     "Acknowledgements")

This text began as my sabbatical project in the winter semester of 2012, during which I wrote most of the material for the first four chapters. For the sabbatical leave, I am indebted to Grand Valley State University for its support of the project, as well as to my colleagues in the Department of Mathematics and the College of Liberal Arts and Sciences for their endorsement of the project. I'm also grateful to the AIM Open Textbook Initiative, sponsored by the ◊link["https://textbooks.aimath.org/"]{American Institute of Mathematics}, for their support of open textbooks generally and their support of this one in particular.

The beautiful full-color .eps graphics in the text are only possible because of David Austin of GVSU and Bill Casselman of the University of British Columbia. Building on their longstanding efforts to develop tools for high quality mathematical graphics, David wrote a library of Python routines that employ ◊link["https://gvsu.edu/s/bi"]{Bill's PiScript program}; David's routines are so easy to use that even I could generate graphics like the professionals that he and Bill are. I am deeply grateful to them both.

The current .html version of the text is possible only because of the amazing work of Rob Beezer and his development of the original Mathbook XML, now known as ◊link["https://pretextbook.org/"]{PreTeXt}. My ability to take advantage of Rob's work is due in large part to the support of the American Institute of Mathematics, which funded me to attend a weeklong workshop in Mathbook XML in San Jose, CA, in April 2016, as well as the support of the ongoing ◊link["https://groups.google.com/g/pretext-support"]{user group}. A subsequent workshop in June 2019 has offered further support and more improvements to the text.

David Farmer's conversion script saved me hundreds of hours of work by taking my original LaTeX source and converting it to PreTeXt; David remains a major source of ongoing support and advocacy. Alex Jordan of Portland Community College has also been a tremendous help, and it is through Alex's fantastic work that live WeBWorK exercises are not only possible, but also included from the 2017 version forward. Mitch Keller of Morningside College agreed in early 2018 to serve as the book's production editor; his technical expertise has contributed to many aspects of the book, including the presence of answers to activities and non- WeBWorK exercises and other supporting material for instructors.

For the 2018 edition, Kathy Yoshiwara of the AIM Editorial Board read the entire text and contributed editorial suggestions for every section. In short, she made the prose cleaner, more direct, and simply better. I'm deeply thankful for her time, effort, and insights.

Over my more than 20 years at GVSU, many of my colleagues have shared with me ideas and resources for teaching calculus. I am particularly indebted to David Austin, Will Dickinson, Paul Fishback, Jon Hodge, and Steve Schlicker for their contributions that improved my teaching of and thinking about calculus, including materials that I have modified and used over many different semesters with students. Parts of these ideas can be found throughout this text. In addition, Will Dickinson and Steve Schlicker provided me access to a large number of their electronic notes and activities from teaching of differential and integral calculus, and those ideas and materials have similarly impacted my work and writing in positive ways, with some of their problems and approaches finding parallel presentation here.

In the summer of 2012, David and Steve each agreed to write a chapter to support the completion of the material on integral calculus. David is the lead author of ◊link["https://activecalculus.org/single/C-7.html"]{Chapter 7} and Steve the lead author of ◊link["https://activecalculus.org/single/C-8.html"]{Chapter 8}. Along with our colleague Ted Sundstrom, Steve has also contributed a large number of problem and activity solutions and answers. I'm especially grateful for how the work of these friends and colleagues has made the text so much better.

Shelly Smith of GVSU and Matt DeLong of Marian University both provided extensive comments on the first few chapters of early drafts, feedback that was immensely helpful in improving the text. As more and more people use the text, I am grateful to everyone who reads, edits, and uses this book, and hence contributes to its improvement through ongoing discussion.

Finally, I am grateful for all that my students have taught me over the years. Their responses and feedback have helped to shape me as a teacher, and I appreciate their willingness to wholeheartedly engage in the activities and approaches I've tried in class, to let me know how those affect their learning, and to help me learn and grow as an instructor. Early on, they also provided useful editorial feedback on this text.

Any and all remaining errors or inconsistencies are mine. I will gladly take ◊link["https://gvsu.edu/s/0vK"]{reader and user feedback} to correct them, along with other suggestions to improve the text.